try(require("shiny")||install.packages("shiny"))
try(require("cluster")||install.packages("cluster"))
try(require("ggbiplot")||install.packages("ggbiplot"))
try(require("mclust")||install.packages("mclust"))
try(require("MASS")||install.packages("MASS"))

library("shiny")
library("cluster")
library("ggbiplot")
library("mclust")
library("MASS")